#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCalc
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CalcInfo")]
	public partial class CalcToSQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCalcInfo(CalcInfo instance);
    partial void UpdateCalcInfo(CalcInfo instance);
    partial void DeleteCalcInfo(CalcInfo instance);
    #endregion
		
		public CalcToSQLDataContext() : 
				base(global::WpfCalc.Properties.Settings.Default.CalcInfoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CalcToSQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CalcToSQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CalcToSQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CalcToSQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CalcInfo> CalcInfos
		{
			get
			{
				return this.GetTable<CalcInfo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CalcInfo")]
	public partial class CalcInfo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _resID;
		
		private System.Nullable<decimal> _tal1;
		
		private System.Nullable<decimal> _tal2;
		
		private string _metode;
		
		private System.Nullable<decimal> _resultat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnresIDChanging(int value);
    partial void OnresIDChanged();
    partial void Ontal1Changing(System.Nullable<decimal> value);
    partial void Ontal1Changed();
    partial void Ontal2Changing(System.Nullable<decimal> value);
    partial void Ontal2Changed();
    partial void OnmetodeChanging(string value);
    partial void OnmetodeChanged();
    partial void OnresultatChanging(System.Nullable<decimal> value);
    partial void OnresultatChanged();
    #endregion
		
		public CalcInfo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int resID
		{
			get
			{
				return this._resID;
			}
			set
			{
				if ((this._resID != value))
				{
					this.OnresIDChanging(value);
					this.SendPropertyChanging();
					this._resID = value;
					this.SendPropertyChanged("resID");
					this.OnresIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tal1", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> tal1
		{
			get
			{
				return this._tal1;
			}
			set
			{
				if ((this._tal1 != value))
				{
					this.Ontal1Changing(value);
					this.SendPropertyChanging();
					this._tal1 = value;
					this.SendPropertyChanged("tal1");
					this.Ontal1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tal2", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> tal2
		{
			get
			{
				return this._tal2;
			}
			set
			{
				if ((this._tal2 != value))
				{
					this.Ontal2Changing(value);
					this.SendPropertyChanging();
					this._tal2 = value;
					this.SendPropertyChanged("tal2");
					this.Ontal2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_metode", DbType="VarChar(10)")]
		public string metode
		{
			get
			{
				return this._metode;
			}
			set
			{
				if ((this._metode != value))
				{
					this.OnmetodeChanging(value);
					this.SendPropertyChanging();
					this._metode = value;
					this.SendPropertyChanged("metode");
					this.OnmetodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_resultat", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> resultat
		{
			get
			{
				return this._resultat;
			}
			set
			{
				if ((this._resultat != value))
				{
					this.OnresultatChanging(value);
					this.SendPropertyChanging();
					this._resultat = value;
					this.SendPropertyChanged("resultat");
					this.OnresultatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
